kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: format
  image: jrei/crystal-alpine
  commands:
  - crystal tool format --check

- name: build
  image: jrei/crystal-alpine
  commands:
  - shards install
  - shards build --static

- name: test
  image: jrei/crystal-alpine
  commands:
  - crystal spec
