kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: format
  image: crystallang/crystal:latest-alpine
  commands:
  - crystal tool format --check

- name: build
  image: crystallang/crystal:latest-alpine
  volumes:
  - name: cache
    path: /root/.cache
  commands:
  - shards install
  - shards build --static

- name: lint
  image: crystallang/crystal:latest-alpine
  commands:
  - bin/ameba

- name: test
  volumes:
  - name: cache
    path: /root/.cache
  image: crystallang/crystal:latest-alpine
  commands:
  - crystal spec -D allow_root --warnings all --error-on-warnings

- name: build docs
  image: crystallang/crystal:latest-alpine
  volumes:
  - name: docs
    path: /docs
  commands:
  - crystal docs -o /docs

- name: publish docs
  image: jrei/gh-pages-ci
  volumes:
  - name: docs
    path: /docs
  environment:
    GIT_USER: Drone CI
    GIT_COMMIT_MESSAGE: Update docs
    SITE_TEMP_DIR: /docs
    SSH_PRIVATE_KEY:
      from_secret: ssh_private_key
  when:
    branch: [ master ]

volumes:
- name: cache
  temp: {}
- name: docs
  temp: {}
